name: Bash Script
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test.sh
  test-script:
    needs: [bash-script]
    runs-on: ubuntu-latest
    #environment:
      #name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test1.sh
  A-script:
    needs: [bash-script]
    runs-on: ubuntu-latest
    #environment:
      #name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test1.sh
  B-script:
    needs: [bash-script]
    runs-on: ubuntu-latest
    environment:
      name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test1.sh
  email:
    runs-on: ubuntu-latest
    name: A job to get a users email
    steps:
      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ github.triggering_actor }}
      
  # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.test.outputs.email }}"        
