name: Bash Script
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test.sh
  test-script:
    needs: [bash-script]
    runs-on: ubuntu-latest
    #environment:
      #name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test1.sh
  A-script:
    needs: [bash-script]
    runs-on: ubuntu-latest
    #environment:
      #name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test1.sh
  B-script:
    needs: [bash-script]
    runs-on: ubuntu-latest
    environment:
      name: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash script
        run: bash test1.sh
  email:
    runs-on: ubuntu-latest
    name: A job to get a users email
    steps:
      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ github.triggering_actor }}
      
  # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.test.outputs.email }}"
        
  Send-mail:
      needs: [email]
      runs-on: ubuntu-latest
      name: Sending email
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
    # mail server settings
      server_address: smtp.gmail.com
      server_port: 25
    # user credentials
      username: ${{ steps.test.outputs.email }}
    #password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
      subject: Test ${{ github.job }} execution finished ${{ job.status }}
    # email body as text
      body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
    # comma-separated string, send email to
      to: ${{ steps.test.outputs.email }}
    # from email name
    from: ${{ steps.test.outputs.email }}        
